cask_args appdir: '/Applications'

brew 'anyenv'
brew 'awscli'
brew 'curl'
brew 'direnv'
brew 'fzf'
brew 'git'
brew 'hugo'
brew 'jq'
brew 'neovim'
brew 'ripgrep'  # for grep in (neo)vim
brew 'starship' # for better zsh prompt
brew 'tig'
brew 'tree'
brew 'watch'    # linux 'watch' command
brew 'wget'

cask 'docker'
cask 'spotify'
